In [1]:
#Submitted by Anuj Tyagi

Write a function so that the columns of the output matrix are powers of the input
vector.

The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde.

In [2]:
import numpy as np

def vanderMat(input, N, inc=False):
  input = np.array(input)
  if inc is True:
    out = np.array([ x**(N-i-1) for x in input for i in range(N)]).reshape(input.size, N)
  elif inc is False:
    out = np.array([ x**i for x in input for i in range(N)]).reshape(input.size, N)

  return out

In [3]:
print(vanderMat([1,2,3,4,5], 3, False))

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


Problem Statement 2:

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
the given sequence is defined as follows:

The moving average sequence has n-k+1 elements as shown below.
The moving averages with k=4 of a ten-value sequence (n=10) is shown below

i 1 2 3 4 5 6 7 8 9 10

===== == == == == == == == == == ==

Input 10 20 30 40 50 60 70 80 90 100

y1 25 = (10+20+30+40)/4

y2 35 = (20+30+40+50)/4

y3 45 = (30+40+50+60)/4

y4 55 = (40+50+60+70)/4

y5 65 = (50+60+70+80)/4

y6 75 = (60+70+80+90)/4

y7 85 = (70+80+90+100)/4

Thus, the moving average sequence has n-k+1=10-4+1=7 values.

Question: Write a function to find moving average in an array over a window:

Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [4]:
def moving_avg(inp_array, k):
    n = len(inp_array)
    N = (n - k + 1)
    
    for i in range(N):
        moving_val = 0
        count = 1
        original_i = i
        while(count <= k):
            #print(count, "", "calculating moving avg.")
            moving_val += inp_array[i]
            count += 1
            i += 1
            
        i = original_i
        print(format(moving_val/k,'.3f')," ", end = "")

In [5]:
given_arr = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
arr =  [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
arr2 = [1, 2, 3, 7, 9]
moving_avg(given_arr, 4)
print("")
moving_avg(arr, 3)
print("")
moving_avg(arr2, 3)

25.000  35.000  45.000  55.000  65.000  75.000  85.000  
5.000  4.667  5.667  6.667  9.667  28.667  49.333  72.667  84.000  93.333  116.333  
2.000  4.000  6.333  